### ISSUE TITLE
request: direct binaries for download

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#11166]
Hi,

I've used the cvc5 release directly in a github workflow like so:

```yaml
       - name: Install cvc5 binary
         uses: supplypike/setup-bin@v4
         with:
           uri: 'https://github.com/cvc5/cvc5/releases/download/cvc5-1.2.0/cvc5-${{ matrix.cvc5 }}'
           name: 'cvc5'
           version: '1.0.8'
```

With the latest releases this doesn't work anymore because things are packed into zip files. Any chance to also provide the simple binaries again?
